title: Sravani Namburu
logo: "/images/sravani.jpg"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Engineer with nearly 3 years of experience in SQL, Python, and data visualization tools like Excel, Tableau. Skilled in analyzing complex datasets, creative interactive dashboards, and driving insights from them. Experienced in healthcare and insurance data analytics, leveraging data-driven approaches to address key objectives. 
  <br><br>
  <a href="https://www.linkedin.com/in/sravaninamburu/">View my LinkedIn Profile</a> 


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
